apiVersion: v1alpha1
kind: Cluster
metadata:
  creationTimestamp: 2017-10-03T05:41:02Z
  deletionTimestamp: 2017-10-03T06:14:29Z
  generation: 1507009262665292092
  name: do1
  uid: ACID-K8S-C-hgdrgjxtzebgpa4
spec:
  api:
    advertiseAddress: ""
    bindPort: 6443
  caCertName: ca
  cloud:
    cloudProvider: digitalocean
    instanceImage: ubuntu-16-04-x64
    region: nyc3
    zone: nyc3
  credentialName: do
  frontProxyCACertName: front-proxy-ca
  kubernetesVersion: v1.8.1
  networking:
    networkProvider: calico
    nonMasqueradeCIDR: 10.0.0.0/8
status:
  apiServer:
  - address: ""
    type: ExternalIP
  - address: ""
    type: InternalIP
  cloud: {}
  phase: Deleting
  sshKeyExternalID: d1-ssddan